import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname =
  import.meta.dirname ?? path.dirname(fileURLToPath(import.meta.url));
const previewEnvPath = path.resolve(dirname, "../e2e/.env.e2e-preview");

const convexUrl = process.env.VITE_CONVEX_URL || "";
const convexSiteUrl = process.env.VITE_CONVEX_SITE_URL || "";

if (!convexUrl) {
  console.error(
    "[setup-e2e-preview] Error: VITE_CONVEX_URL is not provided by convex deploy.",
  );
  process.exit(1);
}

const content = [
  "# Generated by setup-e2e-preview.ts - DO NOT EDIT",
  `VITE_CONVEX_URL=${convexUrl}`,
  `VITE_CONVEX_SITE_URL=${convexSiteUrl}`,
  "",
].join("\n");

fs.writeFileSync(previewEnvPath, content, "utf-8");
console.log(`[setup-e2e-preview] Wrote preview URLs to ${previewEnvPath}`);
console.log(`  VITE_CONVEX_URL: ${convexUrl}`);
console.log(`  VITE_CONVEX_SITE_URL: ${convexSiteUrl}`);
