import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname =
  import.meta.dirname ?? path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(dirname, "../../..");
const previewEnvPath = path.resolve(rootDir, "apps/web/e2e/.env.e2e-preview");

const convexUrl = process.env.CONVEX_URL || process.env.VITE_CONVEX_URL || "";
const convexSiteUrl =
  process.env.CONVEX_SITE_URL || process.env.VITE_CONVEX_SITE_URL || "";

if (!convexUrl) {
  console.error(
    "[setup-preview] Error: Neither CONVEX_URL nor VITE_CONVEX_URL is provided by convex deploy.",
  );
  process.exit(1);
}

const content = [
  "# Generated by setup-preview.ts - DO NOT EDIT",
  `VITE_CONVEX_URL=${convexUrl}`,
  `VITE_CONVEX_SITE_URL=${convexSiteUrl}`,
  "",
].join("\n");

fs.writeFileSync(previewEnvPath, content, "utf-8");
console.log(`[setup-preview] Wrote preview URLs to ${previewEnvPath}`);
console.log(`  VITE_CONVEX_URL: ${convexUrl}`);
console.log(`  VITE_CONVEX_SITE_URL: ${convexSiteUrl}`);
