/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicUsageRouteImport } from './routes/(public)/usage'
import { Route as publicTermsOfServiceRouteImport } from './routes/(public)/terms-of-service'
import { Route as publicPrivacyPolicyRouteImport } from './routes/(public)/privacy-policy'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicFaqRouteImport } from './routes/(public)/faq'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appFamilyRouteImport } from './routes/(app)/family'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appRecordsNewRouteImport } from './routes/(app)/records/new'
import { Route as appRecordsIdRouteImport } from './routes/(app)/records/$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicUsageRoute = publicUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsOfServiceRoute = publicTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyPolicyRoute = publicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicFaqRoute = publicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => publicRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appFamilyRoute = appFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appRecordsNewRoute = appRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appRecordsIdRoute = appRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRoute
  '/family': typeof appFamilyRoute
  '/settings': typeof appSettingsRoute
  '/faq': typeof publicFaqRoute
  '/login': typeof publicLoginRoute
  '/privacy-policy': typeof publicPrivacyPolicyRoute
  '/terms-of-service': typeof publicTermsOfServiceRoute
  '/usage': typeof publicUsageRoute
  '/': typeof publicIndexRoute
  '/records/$id': typeof appRecordsIdRoute
  '/records/new': typeof appRecordsNewRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRoute
  '/family': typeof appFamilyRoute
  '/settings': typeof appSettingsRoute
  '/faq': typeof publicFaqRoute
  '/login': typeof publicLoginRoute
  '/privacy-policy': typeof publicPrivacyPolicyRoute
  '/terms-of-service': typeof publicTermsOfServiceRoute
  '/usage': typeof publicUsageRoute
  '/': typeof publicIndexRoute
  '/records/$id': typeof appRecordsIdRoute
  '/records/new': typeof appRecordsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/family': typeof appFamilyRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(public)/faq': typeof publicFaqRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/privacy-policy': typeof publicPrivacyPolicyRoute
  '/(public)/terms-of-service': typeof publicTermsOfServiceRoute
  '/(public)/usage': typeof publicUsageRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/records/$id': typeof appRecordsIdRoute
  '/(app)/records/new': typeof appRecordsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/family'
    | '/settings'
    | '/faq'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/usage'
    | '/'
    | '/records/$id'
    | '/records/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/family'
    | '/settings'
    | '/faq'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/usage'
    | '/'
    | '/records/$id'
    | '/records/new'
  id:
    | '__root__'
    | '/(app)'
    | '/(public)'
    | '/(app)/dashboard'
    | '/(app)/family'
    | '/(app)/settings'
    | '/(public)/faq'
    | '/(public)/login'
    | '/(public)/privacy-policy'
    | '/(public)/terms-of-service'
    | '/(public)/usage'
    | '/(public)/'
    | '/(app)/records/$id'
    | '/(app)/records/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/usage': {
      id: '/(public)/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof publicUsageRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms-of-service': {
      id: '/(public)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof publicTermsOfServiceRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy-policy': {
      id: '/(public)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof publicPrivacyPolicyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/faq': {
      id: '/(public)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof publicFaqRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/family': {
      id: '/(app)/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof appFamilyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/records/new': {
      id: '/(app)/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof appRecordsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/records/$id': {
      id: '/(app)/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof appRecordsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  appFamilyRoute: typeof appFamilyRoute
  appSettingsRoute: typeof appSettingsRoute
  appRecordsIdRoute: typeof appRecordsIdRoute
  appRecordsNewRoute: typeof appRecordsNewRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  appFamilyRoute: appFamilyRoute,
  appSettingsRoute: appSettingsRoute,
  appRecordsIdRoute: appRecordsIdRoute,
  appRecordsNewRoute: appRecordsNewRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicFaqRoute: typeof publicFaqRoute
  publicLoginRoute: typeof publicLoginRoute
  publicPrivacyPolicyRoute: typeof publicPrivacyPolicyRoute
  publicTermsOfServiceRoute: typeof publicTermsOfServiceRoute
  publicUsageRoute: typeof publicUsageRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicFaqRoute: publicFaqRoute,
  publicLoginRoute: publicLoginRoute,
  publicPrivacyPolicyRoute: publicPrivacyPolicyRoute,
  publicTermsOfServiceRoute: publicTermsOfServiceRoute,
  publicUsageRoute: publicUsageRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
